import { concat } from "$lib/tulip/utils/buffer";
import { utf8ToBytes } from "@noble/ciphers/utils";
import { randomBytes } from "@noble/ciphers/webcrypto";
import { pbkdf2 } from "@noble/hashes/pbkdf2";
import { sha512 } from "@noble/hashes/sha2";


// Salt values
// Keep them in sync with the backend
const SALT_PREFIX_MAGIC = "tulip-";
const SALT_PREFIX_LENGTH = 224;
const SALT_PREFIX = SALT_PREFIX_MAGIC.padEnd(SALT_PREFIX_LENGTH, "#");
const SALT_PREFIX_BYTES = utf8ToBytes(SALT_PREFIX);

// Key lengths
const CLIENT_RANDOM_VALUE_LENGTH = 32;

// The derived key length
const DERIVED_KEY_LENGTH = 64;

// The number of iterations for the derived key
// See https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
const DERIVED_KEY_ITERATIONS = 210_000;

// Take only the first 32 bytes of the hashed authentication key
const HASHED_AUTHENTICATION_KEY_LENGTH = 32;

/**
 * Generates a client random value.
 * The client random value will be used to generate the salt.
 */
export function randomClientValue(): Uint8Array {
  return randomBytes(CLIENT_RANDOM_VALUE_LENGTH);
}

/**
 * Generates a salt given a client random value.
 * The salt together with the password will be used for the password-based key derivation function.
 *
 * @param crv Client random value
 * @param prefix Optional prefix
 */
export function generateSalt(crv: Uint8Array, prefix?: Uint8Array): Uint8Array {
  return sha512(concat(prefix, SALT_PREFIX_BYTES.subarray(0, SALT_PREFIX_LENGTH - (prefix?.length ?? 0)), crv));
}

/**
 * Generates the authentication key and the encryption key from the user password and a salt.
 * The derived authentication key is being used to authenticate login requests.
 * The derived encryption key is being used to encrypt the master key.
 *
 * @param password The user password
 * @param salt The salt generated by `generateSalt`
 */
export function generateDerivedKeys(
  password: Uint8Array,
  salt: Uint8Array,
): [derivedEncryptionKey: Uint8Array, derivedAuthenticationKey: Uint8Array] {
  const derivedKey = pbkdf2(sha512, password, salt, { c: DERIVED_KEY_ITERATIONS, dkLen: DERIVED_KEY_LENGTH });
  const derivedEncryptionKey = derivedKey.subarray(0, derivedKey.length / 2);
  const derivedAuthenticationKey = derivedKey.subarray(derivedKey.length / 2);

  return [
    derivedEncryptionKey,
    derivedAuthenticationKey,
  ];
}

/**
 * Generates the hashed authentication key by taking a couple of bytes of the sha512'd derived authentication key.
 * The hashed authentication key is stored on the server, in order to authenticate login requests.
 *
 * @param derivedAuthenticationKey Derived authentication key generated by `generateDerivedKeys`
 */
export function generateHashedAuthenticationKey(derivedAuthenticationKey: Uint8Array): Uint8Array {
  return sha512(derivedAuthenticationKey).subarray(0, HASHED_AUTHENTICATION_KEY_LENGTH);
}
